name: Günlük Piyasa Verisi Güncelleme BIST

on:
  schedule:
    # Her gün gece 00:00 UTC'de çalışır (Türkiye saatiyle 03:00)
    - cron: '0 0 * * *'
  # İstersen GitHub arayüzünden butona basıp elle de çalıştırabilirsin:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek (Checkout)
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Kütüphaneleri Yükle
      run: |
        pip install -r requirements.txt

    - name: Python Scriptini Çalıştır
      run: |
        python fiyat_getirBIST.py

    - name: Değişiklikleri Kaydet ve Gönder (Commit & Push)
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        # data klasöründeki değişiklikleri ekle
        git add data/pazar_verileribist.json
        # Eğer değişiklik varsa commit yap, yoksa hata verme
        git commit -m "Otomatik veri güncellemesi: $(date)" || exit 0
        git push